config/routes.rb
Boot::Application.routes.draw do

  resources :stubs

  namespace 'chargify' do
    match '/hooks' => "hooks#dispatch_handler", :via => "post"
  end  
  
  resources :messages
  match "contact" => "messages#new"

  resources :renters
  match "rent" => "renters#new"

  resources :sellers
  match "sell" => "sellers#new"
  
  resources :buyers
  match "buy" => "buyers#new"

  resources :listings

  resources :leads

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users

  get "pages/index" 
  match "index" => "pages#index"
  
  get "pages/submitted"
  match "submitted" => "pages#submitted", :as => 'submitted_page'

  get "pages/about"
  match "about" => "pages#about"

  get "pages/find"
  match "find" => "pages#find"
  match "find-a-realtor" => "pages#find"
  
  get "pages/agent"
  match "realtors" => "pages#agent"
  
  get "pages/sent_message"
  match "mail_sent" => "pages#sent_message", :as => 'sent_message'

  get "pages/agent"
  match "agents" => "pages#agent"
  
  get "pages/terms_of_use"
  match "terms" => "pages#terms_of_use"
  
  get "pages/privacy_policy"
  match "privacy_policy" => "pages#privacy_policy"
  
  get "users/cpanel"
  match "cpanel" => "users#cpanel", :as => 'user_root'
  
  get "users/index"
  
  get "listings/manage_listings"
  match "manage_listings" => "listings#manage_listings"
  
  get "leads/manage_leads"
  match "manage_leads" => "leads#manage_leads"

  root :to => 'pages#index'

end

app/models/renter.rb
class Renter < ActiveRecord::Base
  validates :bedrooms, :numericality => { :greater_than_or_equal_to => 0 }
  validates :bathrooms, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
  # GET /renters
  # GET /renters.json
  def index
    @renters = Renter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @renters }
    end
  end

  # GET /renters/1
  # GET /renters/1.json
  def show
    @renter = Renter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @renter }
    end
  end

  # GET /renters/new
  # GET /renters/new.json
  def new
    @renter = Renter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @renter }
    end
  end

  # GET /renters/1/edit
  def edit
    @renter = Renter.find(params[:id])
  end

  # POST /renters
  # POST /renters.json
  def create
    @renter = Renter.new(params[:renter])
    @locals = User.where(:city => @buyer.city)
    @users = @locals.random(5)
    respond_to do |format|
      if @renter.save
        @users.each do |user|
          RenterMailer.registration_welcome(@renter, user).deliver
          Renter.increment_counter("times_forwarded", @renter.id)
        end
        format.html { redirect_to :submitted_page, :notice => 'Seller was successfully created.' }
        format.json { render :json => @renter, :status => :created, :location => @renter }
      else
        format.html { render :action => "new" }
        format.json { render :json => @renter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /renters/1
  # PUT /renters/1.json
  def update
    @renter = Renter.find(params[:id])

    respond_to do |format|
      if @renter.update_attributes(params[:renter])
        format.html { redirect_to @renter, :notice => 'Renter was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @renter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /renters/1
  # DELETE /renters/1.json
  def destroy
    @renter = Renter.find(params[:id])
    @renter.destroy

    respond_to do |format|
      format.html { redirect_to renters_url }
      format.json { head :ok }
    end
  end
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/views/renters/_form.html.erb
<div class="leadform">
<%= form_for(@renter) do |f| %>
  <% if @renter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@renter.errors.count, "error") %> prohibited this renter from being saved:</h2>

      <ul>
      <% @renter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :first_name %>&nbsp
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>&nbsp
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :phone, "Phone number" %>&nbsp
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :email %>&nbsp
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :property_type %>&nbsp
    <%= f.select :property_type, [['Detached house','Detached House'],['Townhouse','Townhouse'],['Apartment/Condo','Apartment/Condo'],['Rental','Rental'],['Vacation','Vacation'],['Other','Other']] %>
  </p>
  <p>
    <%= f.label :min_price, "Price range (monthly)"%>&nbsp
    <%= f.select :min_price, [['< $600','< $600'],['$900','$900'],['$1,200','$1,200'],['$1,500','$1,500'],['$1,800','$1,800'],['$2,100','$2,100'],['$2,400','$2,400'],['$2,700','$2,700'],['$3,000','$3,000'],['> $3,000','> $3,000']] %>
to
    <%= f.select :max_price, [['< $600','< $600'],['$900','$900'],['$1,200','$1,200'],['$1,500','$1,500'],['$1,800','$1,800'],['$2,100','$2,100'],['$2,400','$2,400'],['$2,700','$2,700'],['$3,000','$3,000'],['> $3,000','> $3,000']] %>
  </p>
  <p>
    <%= f.label :bedrooms, "Minimum bedrooms" %>&nbsp
    <%= f.number_field :bedrooms, :class=>"small" %>
  </p>
  <p>
    <%= f.label :bathrooms, "Minimum bathrooms" %>&nbsp
    <%= f.number_field :bathrooms, :class=>"small" %>
  </p>
  <p>
    <%= f.label :street_number %>&nbsp
    <%= f.number_field :street_number, :class=>"small" %>
  </p>
  <p>
    <%= f.label :street_name %>&nbsp
    <%= f.text_field :street_name %>
  </p>
  <p>
    <%= f.label :postal_code %>&nbsp
    <%= f.text_field :postal_code %>
  </p>
  <p>
    <%= f.label :city %>&nbsp
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :timeframe, "I'm renting" %>&nbsp
	<%= f.select :timeframe, [['As soon as possible','As soon as possible'],['Within 2 weeks','Within 2 weeks'],['Within 3-4 weeks','Within 3-4 weeks'],['Within 5-7 weeks','Within 5-7 weeks'],['Within 2-4 months','Within 2-4 months'],['More than 5 months from now','More than 5 months from now']] %>
  </p>
  <p>
    <%= f.label :more_info, "More information" %>&nbsp
    <%= f.text_area :more_info, :rows=>"6" %>
  </p>

	<%= f.hidden_field :times_forwarded, :value => "0" %>


  <div class="actions">
    <%= f.submit 'Find me a Realtor!', :class => 'leadsubmit' %>
  </div>
<% end %>
</div>

app/views/renters/edit.html.erb
<h1>Editing renter</h1>

<%= render 'form' %>

<%= link_to 'Show', @renter %> |
<%= link_to 'Back', renters_path %>

app/views/renters/index.html.erb
<h1>Listing renters</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Property type</th>
    <th>Min price</th>
    <th>Max price</th>
    <th>Bedrooms</th>
    <th>Bathrooms</th>
    <th>Street number</th>
    <th>Street name</th>
    <th>Postal code</th>
    <th>City</th>
    <th>Timeframe</th>
    <th>More info</th>
    <th>Times forwarded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @renters.each do |renter| %>
  <tr>
    <td><%= renter.first_name %></td>
    <td><%= renter.last_name %></td>
    <td><%= renter.phone %></td>
    <td><%= renter.email %></td>
    <td><%= renter.property_type %></td>
    <td><%= renter.min_price %></td>
    <td><%= renter.max_price %></td>
    <td><%= renter.bedrooms %></td>
    <td><%= renter.bathrooms %></td>
    <td><%= renter.street_number %></td>
    <td><%= renter.street_name %></td>
    <td><%= renter.postal_code %></td>
    <td><%= renter.city %></td>
    <td><%= renter.timeframe %></td>
    <td><%= renter.more_info %></td>
    <td><%= renter.times_forwarded %></td>
    <td><%= link_to 'Show', renter %></td>
    <td><%= link_to 'Edit', edit_renter_path(renter) %></td>
    <td><%= link_to 'Destroy', renter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Renter', new_renter_path %>

app/views/renters/new.html.erb
<% provide(:title, 'find a realtor to rent a home with') %>
<h1>Find a Realtor</h1>
<br class="clearfloat">
<p>This form is for <strong>renters</strong> <%= link_to "Are you a seller?", new_seller_path %> or <%= link_to "Are you a buyer?", new_buyer_path %></p>
<br>
<br>
<%= render 'form' %>

app/views/renters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @renter.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @renter.last_name %>
</p>

<p>
  <b>Phone:</b>
  <%= @renter.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @renter.email %>
</p>

<p>
  <b>Property type:</b>
  <%= @renter.property_type %>
</p>

<p>
  <b>Min price:</b>
  <%= @renter.min_price %>
</p>

<p>
  <b>Max price:</b>
  <%= @renter.max_price %>
</p>

<p>
  <b>Bedrooms:</b>
  <%= @renter.bedrooms %>
</p>

<p>
  <b>Bathrooms:</b>
  <%= @renter.bathrooms %>
</p>

<p>
  <b>Street number:</b>
  <%= @renter.street_number %>
</p>

<p>
  <b>Street name:</b>
  <%= @renter.street_name %>
</p>

<p>
  <b>Postal code:</b>
  <%= @renter.postal_code %>
</p>

<p>
  <b>City:</b>
  <%= @renter.city %>
</p>

<p>
  <b>Timeframe:</b>
  <%= @renter.timeframe %>
</p>

<p>
  <b>More info:</b>
  <%= @renter.more_info %>
</p>

<p>
  <b>Times forwarded:</b>
  <%= @renter.times_forwarded %>
</p>


<%= link_to 'Edit', edit_renter_path(@renter) %> |
<%= link_to 'Back', renters_path %>