config/routes.rb
Boot::Application.routes.draw do

  resources :stubs

  namespace 'chargify' do
    match '/hooks' => "hooks#dispatch_handler", :via => "post"
  end  
  
  resources :messages
  match "contact" => "messages#new"

  resources :renters
  match "rent" => "renters#new"

  resources :sellers
  match "sell" => "sellers#new"
  
  resources :buyers
  match "buy" => "buyers#new"

  resources :listings

  resources :leads

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users

  get "pages/index" 
  match "index" => "pages#index"
  
  get "pages/submitted"
  match "submitted" => "pages#submitted", :as => 'submitted_page'

  get "pages/about"
  match "about" => "pages#about"

  get "pages/find"
  match "find" => "pages#find"
  match "find-a-realtor" => "pages#find"
  
  get "pages/agent"
  match "realtors" => "pages#agent"
  
  get "pages/sent_message"
  match "mail_sent" => "pages#sent_message", :as => 'sent_message'

  get "pages/agent"
  match "agents" => "pages#agent"
  
  get "pages/terms_of_use"
  match "terms" => "pages#terms_of_use"
  
  get "pages/privacy_policy"
  match "privacy_policy" => "pages#privacy_policy"
  
  get "users/cpanel"
  match "cpanel" => "users#cpanel", :as => 'user_root'
  
  get "users/index"
  
  get "listings/manage_listings"
  match "manage_listings" => "listings#manage_listings"
  
  get "leads/manage_leads"
  match "manage_leads" => "leads#manage_leads"

  root :to => 'pages#index'

end

app/models/seller.rb
class Seller < ActiveRecord::Base
  validates :bedrooms, :numericality => { :greater_than_or_equal_to => 0 }
  validates :bathrooms, :numericality => { :greater_than_or_equal_to => 0 }
  validates :street_number, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sellers }
    end
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @seller = Seller.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @seller }
    end
  end

  # GET /sellers/new
  # GET /sellers/new.json
  def new
    @seller = Seller.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @seller }
    end
  end

  # GET /sellers/1/edit
  def edit
    @seller = Seller.find(params[:id])
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(params[:seller])
    @locals = User.where(:city => @seller.city)
    @users = @locals.random(5)
    respond_to do |format|
      if @seller.save
        @users.each do |user|
          SellerMailer.registration_welcome(@seller, user).deliver
          Seller.increment_counter("times_forwarded", @seller.id)
        end
        format.html { redirect_to :submitted_page, :notice => 'Seller was successfully created.' }
        format.json { render :json => @seller, :status => :created, :location => @seller }
      else
        format.html { render :action => "new" }
        format.json { render :json => @seller.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sellers/1
  # PUT /sellers/1.json
  def update
    @seller = Seller.find(params[:id])

    respond_to do |format|
      if @seller.update_attributes(params[:seller])
        format.html { redirect_to @seller, :notice => 'Seller was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @seller.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller = Seller.find(params[:id])
    @seller.destroy

    respond_to do |format|
      format.html { redirect_to sellers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<div class="leadform">

<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name %>&nbsp
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>&nbsp
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :phone, "Phone number" %>&nbsp
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :email %>&nbsp
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :property_type %>&nbsp
    <%= f.select :property_type, [['Detached house','Detached House'],['Townhouse','Townhouse'],['Apartment/Condo','Apartment/Condo'],['Rental','Rental'],['Vacation','Vacation'],['Other','Other']] %>
  </p>
  <p>
    <%= f.label :min_price, "Price range"%>&nbsp
    <%= f.select :min_price, [['$50,000','$50,000'],['$100,000','$100,000'],['$200,000','$200,000'],['$300,000','$300,000'],['$400,000','$400,000'],['$500,000','$500,000'],['$600,000','$600,000'],['$700,000','$700,000'],['$800,000','$800,000'],['$900,000','$900,000']] %>
to
    <%= f.select :max_price, [['$200,000','$200,000'],['$300,000','$300,000'],['$400,000','$400,000'],['$500,000','$500,000'],['$600,000','$600,000'],['$700,000','$700,000'],['$800,000','$800,000'],['$900,000','$900,000'],['$1,000,000','$1,000,000'],['$1,250,000','$1,250,000'],['$1,500,000+','$1,500,000']] %>
  </p>
  <p>
    <%= f.label :bedrooms, "Number of bedrooms" %>&nbsp
    <%= f.number_field :bedrooms %>
  </p>
  <p>
    <%= f.label :bathrooms, "Number of bathrooms" %>&nbsp
    <%= f.number_field :bathrooms %>
  </p>
  <p>
    <%= f.label :street_number %>&nbsp
    <%= f.number_field :street_number %>
  </p>
  <p>
    <%= f.label :street_name %>&nbsp
    <%= f.text_field :street_name %>
  </p>
  <p>
    <%= f.label :postal_code %>&nbsp
    <%= f.text_field :postal_code %>
  </p>
  <p>
    <%= f.label :city %>&nbsp
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :timeframe, "I'm looking to sell" %>&nbsp
	<%= f.select :timeframe, [['As soon as possible','As soon as possible'],['Within 2 weeks','Within 2 weeks'],['Within 3-4 weeks','Within 3-4 weeks'],['Within 5-7 weeks','Within 5-7 weeks'],['Within 2-4 months','Within 2-4 months'],['More than 5 months from now','More than 5 months from now']] %>
  </p>
  <p>
    <%= f.label :more_info, "More information" %>&nbsp
    <%= f.text_area :more_info, :rows=>"6" %>
  </p>

	<%= f.hidden_field :times_forwarded, :value => "0" %>


  <div class="actions">
    <%= f.submit 'Find me a Realtor!', :class => 'leadsubmit' %>
  </div>
<% end %>
</div>
<br>

app/views/sellers/edit.html.erb
<h1>Editing seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<h1>Listing sellers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Property type</th>
    <th>Min price</th>
    <th>Max price</th>
    <th>Bedrooms</th>
    <th>Bathrooms</th>
    <th>City</th>
    <th>Timeframe</th>
    <th>More info</th>
    <th>Street number</th>
    <th>Street name</th>
    <th>Postal code</th>
    <th>Times forwarded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sellers.each do |seller| %>
  <tr>
    <td><%= seller.first_name %></td>
    <td><%= seller.last_name %></td>
    <td><%= seller.phone %></td>
    <td><%= seller.email %></td>
    <td><%= seller.property_type %></td>
    <td><%= seller.min_price %></td>
    <td><%= seller.max_price %></td>
    <td><%= seller.bedrooms %></td>
    <td><%= seller.bathrooms %></td>
    <td><%= seller.city %></td>
    <td><%= seller.timeframe %></td>
    <td><%= seller.more_info %></td>
    <td><%= seller.street_number %></td>
    <td><%= seller.street_name %></td>
    <td><%= seller.postal_code %></td>
    <td><%= seller.times_forwarded %></td>
    <td><%= link_to 'Show', seller %></td>
    <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
    <td><%= link_to 'Destroy', seller, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>Find a Realtor</h1>
<br class="clearfloat">
<p>This form is for <strong>sellers</strong>. <%= link_to "Are you a buyer?", new_buyer_path %></p>
<br>
<br>
<%= render 'form' %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @seller.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @seller.last_name %>
</p>

<p>
  <b>Phone:</b>
  <%= @seller.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @seller.email %>
</p>

<p>
  <b>Property type:</b>
  <%= @seller.property_type %>
</p>

<p>
  <b>Min price:</b>
  <%= @seller.min_price %>
</p>

<p>
  <b>Max price:</b>
  <%= @seller.max_price %>
</p>

<p>
  <b>Bedrooms:</b>
  <%= @seller.bedrooms %>
</p>

<p>
  <b>Bathrooms:</b>
  <%= @seller.bathrooms %>
</p>

<p>
  <b>City:</b>
  <%= @seller.city %>
</p>

<p>
  <b>Timeframe:</b>
  <%= @seller.timeframe %>
</p>

<p>
  <b>More info:</b>
  <%= @seller.more_info %>
</p>

<p>
  <b>Street number:</b>
  <%= @seller.street_number %>
</p>

<p>
  <b>Street name:</b>
  <%= @seller.street_name %>
</p>

<p>
  <b>Postal code:</b>
  <%= @seller.postal_code %>
</p>

<p>
  <b>Times forwarded:</b>
  <%= @seller.times_forwarded %>
</p>


<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>