config/routes.rb
Boot::Application.routes.draw do

  resources :stubs

  namespace 'chargify' do
    match '/hooks' => "hooks#dispatch_handler", :via => "post"
  end  
  
  resources :messages
  match "contact" => "messages#new"

  resources :renters
  match "rent" => "renters#new"

  resources :sellers
  match "sell" => "sellers#new"
  
  resources :buyers
  match "buy" => "buyers#new"

  resources :listings

  resources :leads

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users

  get "pages/index" 
  match "index" => "pages#index"
  
  get "pages/submitted"
  match "submitted" => "pages#submitted", :as => 'submitted_page'

  get "pages/about"
  match "about" => "pages#about"

  get "pages/find"
  match "find" => "pages#find"
  match "find-a-realtor" => "pages#find"
  
  get "pages/agent"
  match "realtors" => "pages#agent"
  
  get "pages/sent_message"
  match "mail_sent" => "pages#sent_message", :as => 'sent_message'

  get "pages/agent"
  match "agents" => "pages#agent"
  
  get "pages/terms_of_use"
  match "terms" => "pages#terms_of_use"
  
  get "pages/privacy_policy"
  match "privacy_policy" => "pages#privacy_policy"
  
  get "users/cpanel"
  match "cpanel" => "users#cpanel", :as => 'user_root'
  
  get "users/index"
  
  get "listings/manage_listings"
  match "manage_listings" => "listings#manage_listings"
  
  get "leads/manage_leads"
  match "manage_leads" => "leads#manage_leads"

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :leads, :dependent => :destroy
  has_many :listings, :dependent => :destroy
  
  validates :about, :length => { :maximum => 2000 }
  validates :quote, :length => { :maximum => 225 }

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :first_name, :last_name, :city, :phone, :company, :quote, :about, :password, :password_confirmation, :remember_me, :avatar
  mount_uploader :avatar, AvatarUploader
  
  def create_subscription_and_setup_account!(account_type)
    @account_type = params[:account_type]
    @product_id = PaymentProcessor.product_id(@account_type)
      json_data = {
        :subscription => {
          :product_id => @product_id,
          :customer_attributes => {
            :first_name => self.first_name,
            :last_name => self.last_name,
            :email => self.email,
            :reference => self.id
          }
        }
      }

      subscription = Chargify::Subscription.create(json_data[:subscription])
      Account.init!(subscription) unless subscription.blank?
  end
  
  # these states are those that Chargify considers to be safe, meaning
    # your users should still be able to login to your application
    ACTIVE_STATES = ['pending', 'trialing', 'assessing', 'active', 'soft_failure', 'past_due']

    # ...

    # this method will almost always be unique to the application itself,
    # but I wanted to show an example implementation just in case it's useful
    def self.init!(subscription, account_state = 'pending')
      user_id = subscription.customer.reference if subscription.customer
      product_handle = subscription.product.handle if subscription.product

      if user_id && product_handle
        user = User.find_by_id(user_id)

        unless user.activated?
          user.apply_default_settings
          user.activate!
        end
      end
    end

    # a series of example convenience methods.....

    def chargify_subscriber_id
      @subscriber_id ||= Chargify::Subscription.find_by_customer_reference(user_id).id
    end

    def active?
      ACTIVE_STATES.include?(self.state) || self.exempt?
    end

    def inactive?
      !self.active?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:show, :index]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
    @title = "index realtors"
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @listings = @user.listings
    @json = @listings.all.to_gmaps4rails

    render :layout => 'profile'
    @title = "realtor profile"
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
    @title = "register"
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    render :layout => "cpanel"
    @title = "edit profile"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to edit_user_path(@user), :notice => 'All signed up. Now you just need to fill out your public profile.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'Your profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def cpanel
    render :layout => "cpanel"
    @title = "Realtor control panel"
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/views/users/_form.html.erb
<div class="leadform">
<%= form_for @user, :html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    


  <p><%= f.label :first_name %> &nbsp
  <%= f.text_field :first_name %></p>

  <p><%= f.label :last_name %> &nbsp
  <%= f.text_field :last_name %></p>

  <p><%= f.label :city %> &nbsp
  <%= f.text_field :city %></p>

  <p><%= f.label :company %> &nbsp
  <%= f.text_field :company %></p>

  <p><%= f.label :email %> &nbsp
  <%= f.email_field :email %></p>

  <p><%= f.label :phone %> &nbsp
  <%= f.text_field :phone %></p>

  <p><%= f.label :quote %> &nbsp
  <%= f.text_field :quote %></p>

  <p><%= f.label :about %> &nbsp
  <%= f.text_area :about, :cols => "30", :rows => "7", :class => "xxlarge" %></p>

  <p>Avatar upload</p> &nbsp
  <%= f.file_field :avatar %>
<br class="clearfloat">
<br>
  <% if action_name == "new" %>
  <p><%= f.label :password, "New password" %> &nbsp
  <%= f.password_field :password, :class => "input required"%></p>

  <p><%= f.label :password_confirmation, "Confirm password" %> &nbsp
  <%= f.password_field :password_confirmation %></p>
  <% end %>

<br>
  <div class="actions">
    <%= f.submit "Update profile!", :class => "leadsubmit" %>
  </div>
<% end %>
</div>

app/views/users/_passwords.html.erb
<div class="leadform">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <p><%= f.label :password, "New password" %> &nbsp
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation, "Confirm password" %> &nbsp
  <%= f.password_field :password_confirmation %></p>

  <div class="actions">
    <%= f.submit "Change password", :class => "leadsubmit" %>
  </div>
<% end %>
</div>

app/views/users/cpanel.html.erb
<h1>Control Panel</h1><br class="clearfloat">
	<p>From here, you can edit your profile, manage your listings as well as track your leads.</p>
<br>
<br>

<div id="features">
<h2>Manage Profile</h2>
   <div class="featureList">
	   <div class="cpanelitem">
           <h3><%= link_to "View your profile", user_path(current_user) %></h3>
           <p>Take a look at your profile the way the public sees it.</p>
       </div>
    
        <div class="cpanelitem">
            <h3><%= link_to "Edit your profile", edit_user_path(current_user) %></h3>
            <p>Change details, update your information or change your profile picture here. </p>
        </div>
    <br class="cleafloat" />
    </div><!-- /featureList -->

</div><!-- /#features -->

<div id="features">
<h2>Manage Listings</h2>
   <div class="featureList">
	   <div class="cpanelitem">
           <h3><%= link_to "View your listings", "/manage_listings" %></h3>
           <p>View an index of all of your listings here.</p>
       </div>
    
        <div class="cpanelitem">
            <h3><%= link_to "Add a new listing", new_listing_path %></h3>
            <p>Submit a new listing of yours. Your listings are automatically added to your profile.</p>
        </div>
    <br class="cleafloat" />
    </div><!-- /featureList -->

</div><!-- /#features -->

<div id="features">
<h2>Manage Clients</h2>
   <div class="featureList">
	   <div class="cpanelitem">
           <h3><%= link_to "View your clients", "/manage_leads" %></h3>
           <p>Take a look at your list of clients and leads. Manage all of your clients from a central place and keep organized.</p>
       </div>
    
        <div class="cpanelitem">
            <h3><%= link_to "Add a new client", new_lead_path %></h3>
            <p>Input a new client or lead.</p>
        </div>
    <br class="cleafloat" />
    </div><!-- /featureList -->

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<br>
<%= render 'form' %>
<p></p>
<br>
<br>
<br>
<hr>
<br>
<br>
<h2>Change Password</h2>
<p>Only complete this portion of the form if you want to change your password.</p><br>
<%= render 'passwords' %><br>

app/views/users/index.html.erb
<div class="hero-unit">
    <h1>Realtor Index</h1>
</div>

<table id="users" class="zebra-striped">
	<thead>
		<tr>
			
			<th>First Name</th>
			<th>Last Name</th>
			<th>Company</th>
			<th>City</th>

			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			
			<th><%= user.first_name %></th>
			<th><%= user.last_name %></th>
			<th><%= user.company %></th>
			<th><%= user.city %></th>
			
			<th><%= link_to "View", user_path(user) %></th>
			<th><%= link_to "Edit", edit_user_path(user) %></th>
			<th><%= link_to "Delete", user, :method => :delete, :confirm => "Are you sure?" %></th>
		</tr>
		<% end %>
	</tbody>


</table>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= render 'form' %>

<%= link_to 'All users', users_path %>

app/views/users/show.html.erb
<div class="hero-unit">
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<h3><%= @user.company %></h3>
</div>

<h4>About:</h4>
<p><%= @user.about %></p>
<br>
<h4>Listings</h4>
<table class="zebra-striped">
  <tr>
	<th></th>
    <th>Street number</th>
    <th>Street name</th>
    <th>Title</th>
    <th>City</th>
    <th>Asking price</th>
    <th></th>
  </tr>
<% @user = User.find(params[:id]) %>
<% @listings = @user.listings %>
<% @listings.each do |listing| %>
  <tr>
	<td><%= image_tag listing.img_url(:thumb), :height => "50%" %></td>
    <td><%= listing.street_number %></td>
    <td><%= listing.street_name %></td>
    <td><%= listing.title %></td>
    <td><%= listing.city %></td>
    <td><%= listing.asking_price %></td>
    <td><%= link_to 'Show', listing %></td>
  </tr>
<% end %>
</table>