config/routes.rb
Boot::Application.routes.draw do

  resources :stubs

  namespace 'chargify' do
    match '/hooks' => "hooks#dispatch_handler", :via => "post"
  end  
  
  resources :messages
  match "contact" => "messages#new"

  resources :renters
  match "rent" => "renters#new"

  resources :sellers
  match "sell" => "sellers#new"
  
  resources :buyers
  match "buy" => "buyers#new"

  resources :listings

  resources :leads

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :users

  get "pages/index" 
  match "index" => "pages#index"
  
  get "pages/submitted"
  match "submitted" => "pages#submitted", :as => 'submitted_page'

  get "pages/about"
  match "about" => "pages#about"

  get "pages/find"
  match "find" => "pages#find"
  match "find-a-realtor" => "pages#find"
  
  get "pages/agent"
  match "realtors" => "pages#agent"
  
  get "pages/sent_message"
  match "mail_sent" => "pages#sent_message", :as => 'sent_message'

  get "pages/agent"
  match "agents" => "pages#agent"
  
  get "pages/terms_of_use"
  match "terms" => "pages#terms_of_use"
  
  get "pages/privacy_policy"
  match "privacy_policy" => "pages#privacy_policy"
  
  get "users/cpanel"
  match "cpanel" => "users#cpanel", :as => 'user_root'
  
  get "users/index"
  
  get "listings/manage_listings"
  match "manage_listings" => "listings#manage_listings"
  
  get "leads/manage_leads"
  match "manage_leads" => "leads#manage_leads"

  root :to => 'pages#index'

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  validates :bedrooms, :numericality => { :greater_than_or_equal_to => 0 }
  validates :bathrooms, :numericality => { :greater_than_or_equal_to => 0 }
  validates :street_number, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @buyers }
    end
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
    @buyer = Buyer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @buyer }
    end
  end

  # GET /buyers/new
  # GET /buyers/new.json
  def new
    @buyer = Buyer.new
    @title = "buyers form"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @buyer }
    end
  end

  # GET /buyers/1/edit
  def edit
    @buyer = Buyer.find(params[:id])
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(params[:buyer])
    @locals = User.where(:city => @buyer.city)
    @users = @locals.random(5)
    respond_to do |format|
      if @buyer.save
        @users.each do |user|
          BuyerMailer.registration_welcome(@buyer, user).deliver
          Buyer.increment_counter("times_forwarded", @buyer.id)
        end
        format.html { redirect_to :submitted_page, :notice => 'Seller was successfully created.' }
        format.json { render :json => @buyer, :status => :created, :location => @buyer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @buyer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /buyers/1
  # PUT /buyers/1.json
  def update
    @buyer = Buyer.find(params[:id])

    respond_to do |format|
      if @buyer.update_attributes(params[:buyer])
        format.html { redirect_to @buyer, :notice => 'Buyer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @buyer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer = Buyer.find(params[:id])
    @buyer.destroy

    respond_to do |format|
      format.html { redirect_to buyers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.erb
<div class="leadform">
<%= form_for(@buyer) do |f| %>
  <% if @buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
      <% @buyer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :first_name %>&nbsp
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>&nbsp
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :phone, "Phone number" %>&nbsp
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :email %>&nbsp
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :property_type %>&nbsp
    <%= f.select :property_type, [['Detached house','Detached House'],['Townhouse','Townhouse'],['Apartment/Condo','Apartment/Condo'],['Rental','Rental'],['Vacation','Vacation'],['Other','Other']] %>
  </p>
  <p>
    <%= f.label :min_price, "Price range"%>&nbsp
    <%= f.select :min_price, [['$50,000','$50,000'],['$100,000','$100,000'],['$200,000','$200,000'],['$300,000','$300,000'],['$400,000','$400,000'],['$500,000','$500,000'],['$600,000','$600,000'],['$700,000','$700,000'],['$800,000','$800,000'],['$900,000','$900,000']] %>
to
    <%= f.select :max_price, [['$200,000','$200,000'],['$300,000','$300,000'],['$400,000','$400,000'],['$500,000','$500,000'],['$600,000','$600,000'],['$700,000','$700,000'],['$800,000','$800,000'],['$900,000','$900,000'],['$1,000,000','$1,000,000'],['$1,250,000','$1,250,000'],['$1,500,000+','$1,500,000']] %>
  </p>
  <p>
    <%= f.label :bedrooms, "Minimum bedrooms" %>&nbsp
    <%= f.number_field :bedrooms, :class=>"small" %>
  </p>
  <p>
    <%= f.label :bathrooms, "Minimum bathrooms" %>&nbsp
    <%= f.number_field :bathrooms, :class=>"small" %>
  </p>
  <p>
    <%= f.label :street_number %>&nbsp
    <%= f.number_field :street_number, :class=>"small" %>
  </p>
  <p>
    <%= f.label :street_name %>&nbsp
    <%= f.text_field :street_name %>
  </p>
  <p>
    <%= f.label :postal_code %>&nbsp
    <%= f.text_field :postal_code %>
  </p>
  <p>
    <%= f.label :city %>&nbsp
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :timeframe, "I'm buying" %>&nbsp
	<%= f.select :timeframe, [['As soon as possible','As soon as possible'],['Within 2 weeks','Within 2 weeks'],['Within 3-4 weeks','Within 3-4 weeks'],['Within 5-7 weeks','Within 5-7 weeks'],['Within 2-4 months','Within 2-4 months'],['More than 5 months from now','More than 5 months from now']] %>
  </p>
  <p>
    <%= f.label :more_info, "More information" %>&nbsp
    <%= f.text_area :more_info, :rows=>"6" %>
  </p>

	<%= f.hidden_field :times_forwarded, :value => "0" %>


  <div class="actions">
    <%= f.submit 'Find me a Realtor!', :class => 'leadsubmit' %>
  </div>
<% end %>
</div>

app/views/buyers/edit.html.erb
<h1>Editing buyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

app/views/buyers/index.html.erb
<h1>Listing buyers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Property type</th>
    <th>Min price</th>
    <th>Max price</th>
    <th>Bedrooms</th>
    <th>Bathrooms</th>
    <th>City</th>
    <th>Timeframe</th>
    <th>More info</th>
    <th>Street number</th>
    <th>Street name</th>
    <th>Postal code</th>
    <th>Times forwarded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buyers.each do |buyer| %>
  <tr>
    <td><%= buyer.first_name %></td>
    <td><%= buyer.last_name %></td>
    <td><%= buyer.phone %></td>
    <td><%= buyer.email %></td>
    <td><%= buyer.property_type %></td>
    <td><%= buyer.min_price %></td>
    <td><%= buyer.max_price %></td>
    <td><%= buyer.bedrooms %></td>
    <td><%= buyer.bathrooms %></td>
    <td><%= buyer.city %></td>
    <td><%= buyer.timeframe %></td>
    <td><%= buyer.more_info %></td>
    <td><%= buyer.street_number %></td>
    <td><%= buyer.street_name %></td>
    <td><%= buyer.postal_code %></td>
    <td><%= buyer.times_forwarded %></td>
    <td><%= link_to 'Show', buyer %></td>
    <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
    <td><%= link_to 'Destroy', buyer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<% provide(:title, 'find a realtor to buy a home with') %>
<h1>Find a Realtor</h1>
<br class="clearfloat">
<p>This form is for <strong>buyers</strong> <%= link_to "Are you a seller?", new_seller_path %></p>
<br>
<br>
<%= render 'form' %>

app/views/buyers/show.html.erb
<% provide(:title, 'view lead') %>
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @buyer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @buyer.last_name %>
</p>

<p>
  <b>Phone:</b>
  <%= @buyer.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @buyer.email %>
</p>

<p>
  <b>Property type:</b>
  <%= @buyer.property_type %>
</p>

<p>
  <b>Min price:</b>
  <%= @buyer.min_price %>
</p>

<p>
  <b>Max price:</b>
  <%= @buyer.max_price %>
</p>

<p>
  <b>Bedrooms:</b>
  <%= @buyer.bedrooms %>
</p>

<p>
  <b>Bathrooms:</b>
  <%= @buyer.bathrooms %>
</p>

<p>
  <b>City:</b>
  <%= @buyer.city %>
</p>

<p>
  <b>Timeframe:</b>
  <%= @buyer.timeframe %>
</p>

<p>
  <b>More info:</b>
  <%= @buyer.more_info %>
</p>

<p>
  <b>Street number:</b>
  <%= @buyer.street_number %>
</p>

<p>
  <b>Street name:</b>
  <%= @buyer.street_name %>
</p>

<p>
  <b>Postal code:</b>
  <%= @buyer.postal_code %>
</p>

<p>
  <b>Times forwarded:</b>
  <%= @buyer.times_forwarded %>
</p>


<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>